### ISSUE TITLE
Right-click menu not recorded when recording a single window

### ISSUE THREAD

**Issue by yawns** [Mnpn/Azayaka#10]
When recording a single window, the right-click menu isn't captured in the recording. Kind of hard to show since the thing is invisible, but here's two recordings, one in Firefox and one in iTerm, accompanied by screenshots of what I was seeing during the recording.

https://github.com/Mnpn/Azayaka/assets/2416785/cd42572e-0499-4fc9-bf48-7a8ffc7c6d06

https://github.com/Mnpn/Azayaka/assets/2416785/bab36ced-3c07-4ce5-9ba4-65a341bc7454

<img width="1512" alt="Screenshot 2024-03-27 at 10 40 05 PM" src="https://github.com/Mnpn/Azayaka/assets/2416785/650ec7cc-c6d1-4c47-af30-2177f0945795">

<img width="1512" alt="Screenshot 2024-03-27 at 10 41 07 PM" src="https://github.com/Mnpn/Azayaka/assets/2416785/89981765-061a-4888-948c-1ea4d10d5dfb">

Weirdly, the menu is captured if you record the full screen.

I'm guessing this is a MacOS problem and not something that can be addressed here, but figured I'd report it anyway. I'm using Sonoma 14.4.1.

**Comment by Mnpn** [comment]
Hi! Indeed - when recording a window you record that window specifically, and thus not any menues or such which appear above it (it behaves the same as when taking screenshots of a window in macOS). Recording the whole screen captures the full screen. I'm not aware of a way to include menues in window recordings - I don't think this is something ScreenCaptureKit offers as it appears to be working as designed by Apple (but feel free to correct me if I am wrong ^^)
