### ISSUE TITLE
How do I run this app?

### ISSUE THREAD

**Issue by di3italis** [Mnpn/Azayaka#11]
I can't find any help or tips on how to actually use this...please help :)

**Comment by Mnpn** [comment]
Hi! After running the .app, the app will show up in the menu bar as a circular icon. Clicking it reveals a menu where you can select a window or a display to record. You can then stop a recording by clicking on the same menu icon and selecting "Stop Recording"!

**Comment by fedegratti** [comment]
Hi @Mnpn one question, I'm trying to run your project locally, but every time I hit the play button on Xcode, the app asks me for permissions. It keeps happening even after I gave Screen & System Audio Recording permissions. It's quite annoying to develop. 
Do you know if there is a fix to that? Thank you!

**Comment by Mnpn** [comment]
> Hi @Mnpn one question, I'm trying to run your project locally, but every time I hit the play button on Xcode, the app asks me for permissions. It keeps happening even after I gave Screen & System Audio Recording permissions. It's quite annoying to develop. Do you know if there is a fix to that? Thank you!

Hi! Perhaps you might have to change the development team or such under the project target's Signing & Capabilities settings?

**Comment by fedegratti** [comment]
> > Hi @Mnpn one question, I'm trying to run your project locally, but every time I hit the play button on Xcode, the app asks me for permissions. It keeps happening even after I gave Screen & System Audio Recording permissions. It's quite annoying to develop. Do you know if there is a fix to that? Thank you!
> 
> Hi! Perhaps you might have to change the development team or such under the project target's Signing & Capabilities settings?

ah yes! I just set the development team properly and it worked like a charm. Thank you!

**Comment by Mnpn** [comment]
Sweet! I'm closing this thread as I hope both of the topics have been resolved. Feel free to open a new issue for other questions, that way we don't send notifications to everyone in the thread! :)
