### ISSUE TITLE
Azayaka only updates monitor count on startup

### ISSUE THREAD

**Issue by lihaoyun6** [Mnpn/Azayaka#15]
I have an iPad as a sidecar display,  and Azayaka can correctly identify it.
But when I disconnected the iPad from the Mac, Azayaka still showed two displays in menu.

I saw the following code in `Menu.swift`:
```Swift
func menuWillOpen(_ menu: NSMenu) {
    if streamType == nil { // not recording
     -> updateAvailableContent(buildMenu: false)
        updateMenu()
    }
}
```
Why not use `updateAvailableContent(buildMenu: true)`?

**Comment by Mnpn** [comment]
Hi! Following up on the conversation in #14 - this should be fixed as of 9780acf by observing display device changes. Thanks!
