### ISSUE TITLE
[Feature request] Add HDR support

### ISSUE THREAD

**Issue by Wrestor** [Mnpn/Azayaka#23]
Apple updated ScreenCaptureKit to support capturing HDR video & images. Please add these options too.

**References**
[Capture HDR content with ScreenCaptureKit](https://developer.apple.com/videos/play/wwdc2024/10088/)
[Sample Code/App](https://developer.apple.com/documentation/screencapturekit/capturing_screen_content_in_macos)

**Comment by Mnpn** [comment]
Hi! Sure, this sounds good - thanks for letting me know! I'll have a look at this when I update to Sequoia :-)

**Comment by Mnpn** [comment]
Hi again! I have just released a new update which adds this. Look for the checkbox in the app's settings!
