### ISSUE TITLE
Latest Sonoma update disables launching the app

### ISSUE THREAD

**Issue by enaloha** [Mnpn/Azayaka#26]
As the title says, after installing the security update of Sonoma (14.6.1), Azayaka asks to allow screen recording (which was granted previously). Toggling off and back on still does not allow recording and Azayaka keeps asking for permission. Quitting Azayaka then no longer allows the system to launch it again. It presents a dialog "“Azayaka.app” will damage your computer. You should move it to the Trash." The only options are [Move to Trash] and [Cancel]. Right-click on the app and selecting Open does not allow launching it either.

**Comment by Mnpn** [comment]
Hi! Thanks for letting me know - I've re-built 1.3 and uploaded a new binary to [the release page](https://github.com/Mnpn/Azayaka/releases/tag/v1.3). This should (hopefully) resolve the problem!

**Comment by enaloha** [comment]
Hi Martin,

wow, that was quick. And yes, the new app works perfectly again.  

Thank you so much,     -Reinhold

**Comment by Mnpn** [comment]
Cheers, glad to hear it works :)
