### ISSUE TITLE
System audio recording for language learning

### ISSUE THREAD

**Issue by AntonBadalian** [Mnpn/Azayaka#29]
Hey, Is it possible to use Azayaka to record the system audio by clicking a keybind such as F3 to start and stop recording and then automatically saving it to the clipboard so you can then paste it into a program such as Anki in order to learn languages such as Japanese?

**Comment by Mnpn** [comment]
Hi! You can make custom keyboard shortcuts in the settings, but there is currently no way to copy the recording to the clipboard (without clicking the notification after the recording is finished to focus the file in Finder and hitting command-c) -- if decent UI/UX for saving to the clipboard can be figured out it wouldn't be a bad feature to have!

**Comment by AntonBadalian** [comment]
For now, I just made a fork and directly made it copy to the clipboard all the time after it finishes writing the file to disk. But I do agree that a nice UI would be good to have. Haven't tested to see if it works since I need my friend to compile it with his Mac. Also what are the steps I need to take to compile/build it. Currently I'm getting some issues: 
![xcodeIssues](https://github.com/user-attachments/assets/0323c8fc-c85a-48aa-9968-8d203868ccf0)

**Comment by Mnpn** [comment]
Hi! You'll have to go to Azayaka's project settings (with the blue icon in the left sidebar/file browser) > Signing & Capabilities, and set your development team to an Apple ID you own. You shouldn't need to do anything else to build Azayaka as far as I know.

Regarding the Package file, can I ask which version of Xcode you are on? Perhaps just fixing the development team resolves that too, but maybe the version of Xcode you're on is older than what I use to build the project (Xcode 16), and that's causing issues? Perhaps you can try cleaning the project (Product > Clean Build Folder, shortcut cmd-shift-K) and see if that helps

**Comment by AntonBadalian** [comment]
Hey, I'm willing to pay around $70 USD for this feature to be added to Azayaka. The code for this seems pretty simple but it's incredibly difficult for me to deal with all these XCode issues since I don't have a Mac and have to get my friend to do it on his. I can even offer to help with some of the code but compiling this for me is just too difficult.
