### ISSUE TITLE
Screen recording colours are not true

### ISSUE THREAD

**Issue by rak00001** [Mnpn/Azayaka#30]
Hey hey, first of all – what a belter of a little app, this is the way tech should be – light and free! :)

My issue is that when I record my screen the colours are off. Almost feels like saturation gain has been turned up by 150% and the colours are blowing out (video editing lingo, sorry!)

I'm attaching couple screenshots of an awkward shoulder and hand of a person and yellow backdrop (privacy – can't show their face etc).

This one is how it's supposed to be (and is in reality / filmed clip / in my editing software):
<img width="151" alt="Screenshot 2024-12-10 at 16 54 27" src="https://github.com/user-attachments/assets/b252b8a6-48b7-4356-a29f-a8db42397826">

This one is what Azayaka saved as a screen recording:
<img width="151" alt="Screenshot 2024-12-10 at 16 54 38" src="https://github.com/user-attachments/assets/41dd2cdd-fc4d-488c-927c-9c8cf753aa5b">

Any ideas, am I doing something wrong or is this something to be fixed?

TIA!

**Comment by Mnpn** [comment]
Hi! Thanks for the lovely words, glad you seem to have found it useful!

Is this HDR content? If so, I assume you're using the latest release of Azayaka, which cannot record in HDR. If there is a conversion from HDR to SDR it likely crushes the image. The next release of Azayaka (which I will try to finish and release this week) will feature support for HDR, though! It requires macOS Sequoia and Apple Silicon (Apple's recording API, which Azayaka uses, does not appear to support HDR on Intel). If you are on Apple Silicon and would like to try to see if enabling HDR fixes the problem, I've built a [pre-release version you could try](https://github.com/user-attachments/files/18079576/Azayaka.1.4.Release.Candidate.zip)! (I'm planning on upgrading to Apple Silicon but have not yet done so, so I haven't been able to test if recording HDR works as expected. YMMV)

If this doesn't help, can you check if the macOS Screenshot tool's video recorder has the same issue? (It should come up if you just search for "Screenshot" in Spotlight, and then picking to record the screen)

**Comment by rak00001** [comment]
No problems at all, it's getting more and more rare to find well thought out little gems like this! My old pirate heart warms for sure! :)

Sorry about the delay in response – new account and bad notifications. But hey, good news! Screen is recording in true colors now! I am indeed on Silicon, albeit one of the earlier M1 MBPs. Will keep using the pre for now! 

Thank you again for this!

**Comment by Mnpn** [comment]
Haha :) Sweet - great to hear it works! I've just released the update so I'll go ahead and close this issue!

**Comment by kocane** [comment]
@Mnpn no other way to solve this without making the video HDR?
