### ISSUE TITLE
Record own voice while capturing MS TEAMS?

### ISSUE THREAD

**Issue by alegend2k** [Mnpn/Azayaka#7]
Hey there,
can you tell me who I can record my own voice when talking in teams?

**Comment by Mnpn** [comment]
Hi! See #4. Azayaka hasn't supported recording microphone input, but I've just published an update which lets you enable microphone recording to a separate audio track. Keep in mind that not all video players will play several audio channels (at least not by default) - it appears QuickTime does, though. Please track #4 for future discussions about recording both microphone data and system audio to the same channel!
